apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon-openstack
spec:
  destination:
    name: ''
    namespace: ooo-openstack
    server: 'https://kubernetes.default.svc'
  source:
    path: openstack-horizon
    repoURL: 'git@github.com:KameloTT/ooo-common.git'
    targetRevision: HEAD
    directory:
      recurse: false
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
