apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-openstack
spec:
  destination:
    name: ''
    namespace: ooo-openstack
    server: 'https://kubernetes.default.svc'
  source:
    path: openstack-base
    repoURL: 'git@github.com:KameloTT/ooo-common.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
